version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Zipping application files...
      - zip -r application.zip . -x "*.git*" "node_modules/*" "test/*"
      - aws s3 cp application.zip s3://quick-bite/deployment/backend/application.zip
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code...
      - npm run build
  post_build:
    commands:
      - VERSION_LABEL="$CODEBUILD_RESOLVED_SOURCE_VERSION-$(date +%Y%m%d%H%M%S)"
      - echo Build completed on `date`
      - echo Deploying application...
      - aws elasticbeanstalk create-application-version --application-name quick-bite-backend --version-label $VERSION_LABEL --source-bundle S3Bucket=quick-bite,S3Key=deployment/backend/application.zip
      - aws elasticbeanstalk update-environment --application-name quick-bite-backend --environment-name quick-bite-backend-prod-env --version-label $VERSION_LABEL

artifacts:
  files:
    - '**/*'
